project:
  type: book

book:
  title: "Lab accessibility in the Faculty of Science"
  author: "Skylight team"
  chapters:
    - index.qmd
    - cfa.qmd
    - data.qmd

format:
  html:
    theme: styles/theme.scss
    toc: true
