# Data

## Lab accessibility undergraduate survey

`survey`:

- Qualtrics data from "Lab accessibility in Science---undergraduate student survey March 2026" conducted by Skylight
- The target population was undergraduate students during September 2025 to April 2026 in the Faculty of Science (FoS)
- All student responses were systematically reviewed and coded by Alexis Gonzalez using an inductive coding approach. Codes were generated based on patterns and themes identified within the responses. In some cases, multiple codes were applied to a single response to more accurately capture the complexity of students' ideas. A codebook was developed to document code definitions and ensure consistency throughout the analysis. Following coding, related codes were grouped into broader categories to support thematic analysis. In this vein, some codes were used in more than one question (note: examples were omitted when the code was used more than once).

## Centre for Accessibility

Data was provided by Michael Segovia, project manager at the Centre for Accessibility (CfA) for working with Skylight.

`students`:

- File: `01_Active Students in Faculty of Science + program info September 2024 - August 2025.xlsx`
- ClockWork data
- Period: September 2024 -- August 2025
- CfA did not start collecting program-related information in their system until mid- to late-2025. As a result, only students who remained active in the CfA system at that time appear in this data snapshot. Students who may have graduated and/or de-activated prior to this snapshot would not be included.
- Entries for students in the Faculty of Science registered with CfA

`lab_requests`:

- File: `02_Students with accommodations in Laboratory sections September 2024 - August 2025.xlsx`
- ClockWork data
- Period: September 2024 -- August 2025
- CfA did not start collecting program-related information in their system until mid- to late-2025. As a result, only students who remained active in the CfA system at that time appear in this data snapshot. Students who may have graduated and/or de-activated prior to this snapshot would not be included.
- Number of students with accommodations registered in at least one course section designated as "Laboratory"
- `status` of student's accommodation letter request
  - `No Accommodation Request` students was eligible for accommodations, but did not download a letter
  - `InstructorInfoMissing` indicates that no instructor record is available for that particular section on Workday (probably equivalent to `No Accommodation Request`, will be interpreted as such in analysis below)

`lab_counts`:

- File: `03_CfA Edits - Science_lab_counts_2024W_2025-07-10.xlsx`
- Number of students with accommodations registered in at least one course section designated as "Laboratory"
